# Plot states
PLOT_EMPTY = "empty"
PLOT_LOCKED = "locked"
PLOT_PLANTED = "planted"
PLOT_GROWING = "growing"
PLOT_NEED_WATER = "need_water"
PLOT_MATURE = "mature"

# Crop ids
CROP_STARBUBBLE_RADISH = "starbubble_radish"
CROP_CLOUD_SUGAR_PUMPKIN = "cloud_sugar_pumpkin"
CROP_MOONDEW_MUSHROOM = "moondew_mushroom"

CROP_IDS = [
    CROP_STARBUBBLE_RADISH,
    CROP_CLOUD_SUGAR_PUMPKIN,
    CROP_MOONDEW_MUSHROOM,
]

# Crop stages
CROP_STAGE_SEED = 0
CROP_STAGE_SPROUT = 1
CROP_STAGE_GROWING = 2
CROP_STAGE_MATURE = 3